### PR TITLE
Update to javaparser-core:3.15.14

### PR DESCRIPTION
**Pull request by jessicadeery**
JavaParser.parse is no longer supported. Use StaticJavaParser.parse

### CODE REVIEW

**Comment by jessicadeery** [comment]
@fabiocarvalho777 Please review.

**Comment by fabiocarvalho777** [comment]
@jessicadeery thanks for your contribution. Notice the job to check your PR failed. I realized it probably failed for reasons not related to your changes. Still, would mind taking a look at it please? Also, did butterfly build succeed in your development environment? Thanks.

**Comment by jessicadeery** [comment]
Hi @fabiocarvalho777 I've taken a look at the CI and this does not seem to be caused by my changes. Same failure occurred 6 months ago. I'm not able to build everything in dev. However, I'm a grade newbie and likely just have in issue with my local dev. I was however able to compile and run tests successfully with butterfly-utilities. I've also integrated the butterfly-utilities changes locally with by butterfly extension, and the changes look good.

**Comment by jessicadeery** [comment]
Prior travis ci failure seemed due to oraclejdk8 See: https://travis-ci.community/t/install-of-oracle-jdk-8-failing/3038

I've updated the .travis.yml to use openjdk8

**Pull request merged**
