### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by spetratos**
Releasing 2.5.0

### CODE REVIEW

**Comment by spetratos** [comment]
Build 190 - All tests passed.

**Comment by fabiocarvalho777** [comment]
@spetratos @mmcrockett 

Spiros, you forgot to generate and check-in new javadocs for this new version.
Also, you forgot step [1.v in the release steps](https://github.com/paypal/butterfly/blob/develop/release_steps.md#release-steps).

Would you fix that please?

**Comment by spetratos** [comment]
Yep. forgot to check those in. Just did push to my repo. Will merge.


Can't find our staging repo on Maven central.


Sp



________________________________

**Comment by fabiocarvalho777** [comment]
@spetratos you will have to remove and redo the tag

**Comment by spetratos** [comment]
trying to figure that out.


Sp


________________________________

**Pull request merged**
